server:
  port: 9002
spring:
  application:
    name: ihrm-system #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 2129
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
